//! App services.
pub mod about;
pub mod authentication;
pub mod authorization;
pub mod category;
pub mod hasher;
pub mod proxy;
pub mod settings;
pub mod tag;
pub mod torrent;
pub mod torrent_file;
pub mod user;
