[metadata]
app = "torrust-index"
purpose = "configuration"
schema_version = "2.0.0"

[logging]
#threshold = "off"
#threshold = "error"
#threshold = "warn"
threshold = "info"
#threshold = "debug"
#threshold = "trace"

[tracker]
api_url = "http://tracker:1212"
listed = false
private = true
url = "http://tracker:7070"

[auth]

[database]

[registration]
[registration.email]
