use torrust_index_backend::models::torrent_file::Torrent;

/// The backend does not generate exactly the same torrent that was uploaded.
/// So we need to update the expected torrent to match the one generated by
/// the backend.
pub fn expected_torrent(mut uploaded_torrent: Torrent) -> Torrent {
    // code-review: The backend does not generate exactly the same torrent
    // that was uploaded and created by the `imdl` command-line tool.
    // So we need to update the expected torrent to match the one generated
    // by the backend. For some of them it makes sense (`announce`  and `announce_list`),
    // for others it does not.
    uploaded_torrent.info.private = Some(0);
    uploaded_torrent.announce = Some("udp://tracker:6969".to_string());
    uploaded_torrent.encoding = None;
    uploaded_torrent.announce_list = Some(vec![vec!["udp://tracker:6969".to_string()]]);
    uploaded_torrent.creation_date = None;
    uploaded_torrent.created_by = None;

    uploaded_torrent
}
