// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2026 Torrust project contributors

//! # Test index
//!
//! | Test | Area | Claim |
//! |------|------|-------|
//! | [`empty_buffer_returns_old_kappa`] | risk | A refit with nothing to learn from returns the calibration it was given, unmoved: both constants come back as they went in, the reported movement is zero, neither regime is marked fitted and both effective sample counts are empty. A refit triggered before any labels have arrived is a no-op rather than a reset to whatever the fit's default would be. |
//! | [`synthetic_convergence_kappa_2`] | risk | Given outcomes generated by a known calibration constant, the fit recovers that constant from a starting point well away from it. The search is therefore doing statistics rather than tracking its own initialisation: it finds the scaling that the data actually implies. |
//! | [`regime_separation`] | risk | One buffer holding entries from both regimes, each generated with its own calibration constant, yields two fits that both succeed and end up clearly apart. The regimes are fitted independently, so a sister-dominated score and an anchor-dominated one are not forced to share a scaling that suits neither. |
//! | [`minimum_sample_guard`] | risk | Plenty of entries is not the same as enough of each outcome. A regime with fifty negatives but only two positives is left unfitted and keeps its previous constant, because the minimum is enforced on the positive and negative counts separately. Fitting a sigmoid to data that is one-sided would push the constant to a bound on the strength of two labels. |
//! | [`stub_valued_entries_converge`] | risk | When every score in the buffer is identical the loss surface carries no information about the scaling, and the search still terminates with a finite, positive constant inside its bounds — it drifts to a boundary rather than diverging or returning something unusable. A stub-valued or saturated period leaves calibration harmlessly inert instead of breaking it. |
//! | [`flat_scores_leave_successive_refits_bit_identical`] | risk | A buffer of zero scores is worse than uninformative — it is silent. Every candidate sharpness predicts a half for every row, so the cross-entropy is one constant across the whole search range, and what comes back is not a fit but the bound the iteration walks to while every comparison it makes is a tie. Two buffers sharing nothing else — different lengths, different base rates, different importance — return the same sharpness bit for bit, and the drift between them is not small but exactly nothing. That is what makes a drift bound applied to such a pair vacuous: it is not that the calibration held steady, it is that no calibration was performed, and the bound would pass at any width whatever. The neighbouring tests fit a fixture whose classes overlap for exactly this reason (´tab:assayer:harness-scenario-tolerances´). |
//! | [`overlap_ladder_fit_lands_at_the_interior_optimum`] | risk | Classes whose scores genuinely overlap put the fit at an interior optimum rather than against a search bound: the overlap ladder's fitted constant lands on the root of the stationarity condition its own counts imply, and sits some four units of log-κ clear of either end of the search range. The preceding test is the contrast that gives this one its point — a buffer whose scores carry no information leaves the search resting on a bound, where the returned constant is an artefact of how the iteration breaks a tie and no later assertion about it can discriminate anything. An interior optimum is what makes the fitted constant a statement about the data, and it is the precondition the search's own unimodality argument rests on. |
//! | [`overlap_ladder_drift_bound_admits_and_rejects`] | risk | Multiplying every score by a factor multiplies the fitted constant by that same factor, which is what makes the declared drift bound a two-sided assertion: a four-percent perturbation of the scores moves the constant and stays inside the bound, while a ten-percent one moves it past and the bound rejects it. Both halves are asserted because a bound that only ever sees movement it admits is indistinguishable from a bound that admits everything — the rejecting case is what shows the figure is deciding something (´tab:assayer:harness-scenario-tolerances´). |
//! | [`search_within_bounds`] | risk | A fitted constant never leaves the configured search interval, even when the data was generated by a constant near its lower end. The search brackets the whole of log-space between the two bounds and can only ever narrow inwards, so the operator's limits are a guarantee about the output and not merely a starting hint. |
//! | [`no_nan_in_loss`] | risk | The cross-entropy stays finite across the whole search range even for scores far outside anything the model would ordinarily produce, including a confidently wrong one. The loss takes a logarithm of the predicted probability, so a single saturated score would otherwise contribute an infinity and make every candidate constant look equally bad. |
//! | [`sigmoid_clamped_never_zero_or_one`] | risk | This is why: the calibration sigmoid is held strictly inside the unit interval, at scores of a thousand in either direction as much as at zero. Neither endpoint is ever returned, so the logarithm the loss takes of it and of its complement always has an argument. |
//! | [`precompute_newest_first_recency`] | risk | The recency discount is anchored at the newest entry, which carries full weight, with each older one worth a fixed fraction more of the discount — so the newest entry in a buffer outweighs the oldest. Anchoring at the newest rather than the oldest keeps the weights bounded by one however long the buffer has been running. |
//! | [`buffer_push_evicts_oldest`] | risk | The calibration buffer is bounded and drops from the front: pushing beyond capacity leaves exactly the most recent entries, in order. Memory is therefore fixed however long the instance runs, and what is sacrificed for that is always the oldest evidence — the evidence recency weighting was already discounting most heavily. |
//! | [`delta_cal_log_space`] | risk | How far the calibration moved is measured as the absolute difference of the logarithms, not of the constants themselves. Movement is therefore relative: a step from one to two counts the same as a step from ten to twenty, which is what a downstream threshold on "the calibration has shifted" needs, since the constant is a scaling. |
//! | [`golden_section_terminates`] | risk | A tolerance so tight that floating-point arithmetic can never satisfy it does not hang the search: the iteration cap ends it and a finite constant comes back. The refit runs on the model owner's thread, so a convergence criterion that cannot be met has to cost a bounded number of iterations rather than the instance. |
//! | [`anchor_refit_label_index_updated`] | risk | A refit that actually fitted the anchor regime is recorded against the label count at which it happened, moving the tracker's stamp off its initial zero. The reactivation trigger measures how long the anchor has gone unfitted from that stamp, so a refit that succeeded but was not recorded would make the anchor look permanently overdue. |
//! | [`regime_transition_shared_with_blend`] | risk | Calibration and blending divide the regimes with one shared transition function, agreeing exactly across the weight range rather than approximately. Two copies that drifted apart would mean an entity was blended as one regime and calibrated as another, and the mismatch would show up only as a mis-calibrated probability with nothing pointing at its cause. |
//! | [`delta_cal_exceeds_threshold`] | risk | The reported movement is large enough to be acted on when the calibration genuinely moves: data generated by a constant three times the one in force produces movement past the default drift-reset threshold. The threshold is therefore reachable by an ordinary recalibration, not a bar only a pathological one could clear. |
//! | [`has_sufficient_anchor_samples_true`] | risk | The cheap pre-check admits a buffer that a real fit would accept: a hundred anchor-dominated entries carrying both outcomes clears the minimums. This scan is what decides whether a reactivation refit is worth running at all, so it has to say yes when the anchor really could be fitted. |
//! | [`has_sufficient_anchor_samples_false`] | risk | The check counts each entry by its regime rather than by its existence, so fifty sister-dominated entries contribute almost nothing toward the anchor's minimums and the answer is no. Counting entries outright would report a busy sister-regime instance as having anchor evidence it has never gathered. |
//! | [`sample_floor_reads_undiscounted_count`] | risk | The sample floor reads the undiscounted weighted count — the same quantity the cheap pre-check computes — so an anchor regime whose evidence is old but sufficient is fitted rather than abandoned. Under a recency-discounted floor the same buffer sits in a trap: the pre-check keeps saying refit, the fit keeps refusing, the refit bookkeeping never advances, and a full search runs on every label. Recency belongs to the objective, which tracks the current score distribution; the floor is an evidence census and takes no discount. |
//! | [`snapshot_counts_weighted_below_threshold`] | risk | The published regime counts are weighted samples, not a census against a hard threshold: a buffer whose entries all sit just below the old 0.3 split still reports substantial anchor evidence, because each record enters the anchor count at its transition share times its importance weight. A threshold tally would have reported zero anchor evidence here — and, through the risk basis, no anchor maturity — while the fit's own floor read a weighted count near half the buffer. |
//! | [`sigmoid_clamped_matches_stable_sigmoid`] | risk | The calibration sigmoid is the crate's shared stable sigmoid with a clamp applied, matching it exactly wherever the clamp is not binding. There is one definition of the logistic curve in the package and calibration adds only the log-loss guard on top — a second implementation would eventually disagree with the one deciding probabilities on the assessment path. |
//! | [`golden_section_monotonicity`] | risk | Every iteration of the search strictly narrows the bracket, on real weighted data and in both of the branches the comparison can take. Because the interval only ever shrinks, the loop's progress toward its tolerance is guaranteed by the step itself rather than by the iteration cap catching a search that had stalled. |
//! | [`boundary_convergence_all_positive`] | risk | Data that is adverse wherever the score is high and benign where it is very low drives the constant toward the steep end of its range, because the sharpest sigmoid is the one that best reproduces such a clean separation. The search leaning on a bound is the correct answer for near-separable data rather than a failure to converge. |
//! | [`recency_weighting_dominance`] | risk | When the older and newer halves of the buffer were generated by different calibrations, the fit follows the newer one — landing well past the geometric midpoint the two halves would give if they counted equally. Recency weighting is what makes calibration track a shifting population instead of averaging over its whole history. |
//! | [`calibration_property_decile_bins`] | risk | The probabilities the fitted constant produces mean what they say: sorted into deciles, every bin's mean predicted probability sits close to the rate at which its entries actually turned out adverse. Recovering the right constant is not the goal in itself — the goal is that a host reading a risk of one in five can act as though one in five is what it will be. |

//! Platt calibration fitting (´alg:platt:fitting´).
//!
//! This module performs golden-section-based Platt scaling to calibrate
//! the logistic model's raw scores into well-calibrated probabilities.
//! The algorithm fits two independent κ values — one for the sister-dominated
//! regime and one for the anchor-dominated regime — using per-regime weighted
//! binary cross-entropy as the objective.
//!
//! # Algorithm
//!
//! Three-phase approach:
//! 1. **Pre-scan:** reverse-iterate the buffer to compute per-entry combined
//!    weights (regime × recency × importance). Compute per-regime effective
//!    sample counts.
//! 2. **Per-regime golden section:** for each eligible regime, search
//!    `log κ ∈ [log 0.01, log 100]` to minimise weighted cross-entropy.
//! 3. **Post-fit:** assemble `PlattRefitResult` with `δ_cal = max |ln κ_new − ln κ_old|`.
//!
//! # Cross-References
//!
//! - (´dec:calibration:per-regime-search´) — why the fit is a factored
//!   per-regime search rather than one joint optimisation
//! - (´sec:platt:calibration´) — the calibration division of the risk models
//! - (´dec:health:calibration-settled-cuts´) — when calibration is called
//!   settled, on movement and on count together

use std::collections::VecDeque;

use crate::health::PlattRefitResult;
use crate::numerics::regime_transition;

// ═══════════════════════════════════════════════════════════════════════════════
// Configuration
// ═══════════════════════════════════════════════════════════════════════════════

/// Configuration for Platt calibration fitting.
///
/// The defaults are the specification's (´tab:config:calibration´).
#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PlattConfig {
    /// Calibration buffer capacity. Default: 2,000.
    pub n_cal_buf: usize,
    /// Periodic refit cadence (labels). Default: 200.
    pub n_refit: u32,
    /// Minimum total weighted samples per regime. Default: 30.
    pub n_cal_min: u32,
    /// Minimum positive weighted samples per regime. Default: 3.
    pub n_cal_pos: u32,
    /// Minimum negative weighted samples per regime. Default: 3.
    pub n_cal_neg: u32,
    /// Initial κ for both regimes. Default: 1.0.
    pub kappa_initial: f64,
    /// Search lower bound for κ. Default: 0.01.
    pub kappa_min: f64,
    /// Search upper bound for κ. Default: 100.0.
    pub kappa_max: f64,
    /// Recency weighting factor `γ_cal`. Default: 0.9998, the sister's own
    /// forgetting rate (´tab:risk:forgetting-rates´).
    pub gamma_cal: f64,
    /// Golden section tolerance in log(κ). Default: 1e-4.
    pub golden_tolerance: f64,
    /// Golden section max iterations. Default: 50.
    pub max_golden_iterations: u32,
    /// `δ_cal` threshold for drift accumulator reset. Default: 0.1.
    pub delta_cal_threshold: f64,
}

impl Default for PlattConfig {
    fn default() -> Self {
        Self {
            n_cal_buf: 2_000,
            n_refit: 200,
            n_cal_min: 30,
            n_cal_pos: 3,
            n_cal_neg: 3,
            kappa_initial: 1.0,
            kappa_min: 0.01,
            kappa_max: 100.0,
            gamma_cal: 0.9998,
            golden_tolerance: 1e-4,
            max_golden_iterations: 50,
            delta_cal_threshold: 0.1,
        }
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Calibration Entry & Buffer
// ═══════════════════════════════════════════════════════════════════════════════

/// One entry in the calibration buffer.
///
/// Written at label time (step 14) from `PendingAssessment.risk_basis`
/// and the label's outcome. Consumed by the Platt fitting algorithm
/// (´alg:platt:fitting´).
///
/// # Cross-References
///
/// - (´constr:platt:buffer´) — the buffer this entry is written into and the
///   effective sample counts read from it
/// - (´dec:health:cached-discrimination´) — why the per-axis rows are carried
///   here and read once at refit
#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CalibrationEntry {
    /// Blended risk score `ρ̂_eff` at assessment time.
    pub rho_eff: f64,
    /// Probability-space uncertainty `σ_p̂` at assessment time — the
    /// denominator of the standardised residual empirical coverage
    /// computes per row (´alg:monitoring:empirical-coverage´).
    ///
    /// As reported, so as tempered: the figure recorded here is evidence-only
    /// along that request's own direction, widened by whatever share of the
    /// precision behind it the models' floors were holding up
    /// (´dec:risk:evidence-only-uncertainty´). The refit therefore sees wider
    /// intervals from degraded models and inflates less on their account,
    /// which is the two corrections agreeing rather than double counting: the
    /// share corrects what the model can know about itself, and the refit
    /// corrects what it cannot.
    pub uncertainty: f64,
    /// Anchor blend weight `w` at assessment time.
    pub anchor_weight: f64,
    /// Binary outcome: `true` if valence > 0.
    pub positive: bool,
    /// Importance weight at label time (from step 8).
    // TODO(2026-05-21) ´todo:code:add-label-index-u64-once-the´: Add `label_index: u64` once the
    // model-owner label counter is threaded into calibration entries by the
    // label path (´dec:ordering:label-function´).
    pub importance_weight: f64,
    /// Per-axis (`axis_id`, predicted, actual) pairs for discrimination
    /// metrics (´dec:health:cached-discrimination´).
    /// Empty when no outcome axes exist.
    pub axis_data: Vec<(crate::types::OutcomeAxisId, f64, f64)>,
}

/// Fixed-capacity circular buffer of calibration entries.
///
/// Entries are ordered by insertion time (oldest at front, newest
/// at back). When at capacity, the oldest entry is evicted on push.
///
/// The capacity and eviction are the buffer's own (´constr:platt:buffer´).
#[derive(Clone, Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CalibrationBuffer {
    /// The entries, oldest at front.
    entries: VecDeque<CalibrationEntry>,
    /// Maximum capacity.
    capacity: usize,
}

impl CalibrationBuffer {
    /// Creates a new empty buffer with the given capacity.
    #[must_use]
    pub fn new(capacity: usize) -> Self {
        Self {
            entries: VecDeque::with_capacity(capacity),
            capacity,
        }
    }

    /// Pushes a new entry, evicting the oldest if at capacity.
    pub fn push(&mut self, entry: CalibrationEntry) {
        if self.entries.len() >= self.capacity {
            self.entries.pop_front();
        }
        self.entries.push_back(entry);
    }

    /// Returns the number of entries in the buffer.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Returns `true` if the buffer is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Truncates the buffer to at most `len` entries, removing from the back.
    ///
    /// Used for checkpoint/restore: reverts the buffer to a prior state.
    pub fn truncate(&mut self, len: usize) {
        self.entries.truncate(len);
    }

    /// Returns a double-ended iterator over the entries (oldest first).
    pub fn iter(&self) -> impl DoubleEndedIterator<Item = &CalibrationEntry> {
        self.entries.iter()
    }

    /// Estimates whether the anchor regime has sufficient weighted samples.
    ///
    /// Lightweight O(n) scan used by the anchor-reactivation trigger
    /// (´tab:platt:refit-cadence´) to avoid triggering a full refit when the anchor
    /// regime cannot contribute. It computes the same undiscounted
    /// weighted count the fit's own sample floor reads
    /// (´constr:platt:buffer´), so the scan and the floor agree.
    #[must_use]
    pub fn has_sufficient_anchor_samples(&self, config: &PlattConfig) -> bool {
        let mut total = 0.0;
        let mut positive = 0.0;

        for entry in &self.entries {
            let g = regime_transition(entry.anchor_weight);
            let w = g * entry.importance_weight;
            total += w;
            if entry.positive {
                positive += w;
            }
        }

        let negative = total - positive;
        total >= f64::from(config.n_cal_min) && positive >= f64::from(config.n_cal_pos) && negative >= f64::from(config.n_cal_neg)
    }

    /// Projects the buffer into an immutable snapshot for the published
    /// `ModelSnapshot`.
    ///
    /// The regime counts are weighted sample counts: each record enters
    /// the sister count at `(1 − g(w)) · w_imp` and the anchor count at
    /// `g(w) · w_imp`, so the published quantities are the effective
    /// sample counts the sample floor is read against
    /// (´constr:platt:buffer´).
    ///
    /// # Cross-References
    ///
    /// - (´dec:calibration:per-regime-search´) — the minimum-sample floor these
    ///   published counts are read against
    #[must_use]
    pub fn to_snapshot(&self) -> crate::snapshot::published::CalibrationBufferSnapshot {
        let mut sister = 0.0_f64;
        let mut anchor = 0.0_f64;
        for entry in &self.entries {
            let g = regime_transition(entry.anchor_weight);
            sister = (1.0 - g).mul_add(entry.importance_weight, sister);
            anchor = g.mul_add(entry.importance_weight, anchor);
        }
        crate::snapshot::published::CalibrationBufferSnapshot {
            total_entries: self.entries.len(),
            sister_regime_records: sister,
            anchor_regime_records: anchor,
        }
    }
}

impl Default for CalibrationBuffer {
    fn default() -> Self {
        Self::new(2_000)
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Internal Types
// ═══════════════════════════════════════════════════════════════════════════════

/// Pre-computed weights for a single buffer entry, used during fitting.
struct PrecomputedEntry {
    /// The raw blended risk score `ρ̂_eff`.
    rho: f64,
    /// Whether this was a positive outcome.
    positive: bool,
    /// Combined weight for the sister regime.
    sister_weight: f64,
    /// Combined weight for the anchor regime.
    anchor_weight: f64,
}

/// Selects which regime to fit or count.
#[derive(Clone, Copy, Debug)]
enum RegimeSelector {
    /// Sister-dominated regime (w < 0.3).
    Sister,
    /// Anchor-dominated regime (w ≥ 0.3).
    Anchor,
}

/// Effective sample counts for a single regime.
#[derive(Clone, Copy, Debug)]
struct EffectiveCounts {
    /// Total weighted count.
    total: f64,
    /// Weighted positive count.
    positive: f64,
    /// Weighted negative count.
    negative: f64,
}

impl EffectiveCounts {
    /// Returns `true` if minimum sample requirements are met.
    fn meets_minimums(&self, config: &PlattConfig) -> bool {
        self.total >= f64::from(config.n_cal_min)
            && self.positive >= f64::from(config.n_cal_pos)
            && self.negative >= f64::from(config.n_cal_neg)
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Core Algorithm
// ═══════════════════════════════════════════════════════════════════════════════

/// Performs a full Platt calibration refit.
///
/// Pure function: buffer + old κ values + config → `PlattRefitResult`.
/// No side effects — the caller applies the result to the working copy,
/// convergence tracker, and drift accumulators.
///
/// # Three phases
///
/// 1. **Pre-scan:** compute per-entry combined weights for both regimes.
/// 2. **Per-regime golden section:** fit each eligible regime.
/// 3. **Post-fit:** compute `δ_cal` and assemble result.
///
/// # Cross-References
///
/// - (´alg:platt:fitting´) — the three-phase fit this implements
#[must_use]
#[cfg(test)]
pub fn refit_platt_calibration(
    buffer: &CalibrationBuffer,
    old_kappa_sister: f64,
    old_kappa_anchor: f64,
    config: &PlattConfig,
) -> PlattRefitResult {
    let monitoring = crate::config::types::MonitoringConfig::default();
    refit_platt_calibration_with_monitoring(buffer, old_kappa_sister, old_kappa_anchor, config, &monitoring)
}

/// Performs a Platt refit with host-configured discrimination thresholds.
#[must_use]
pub fn refit_platt_calibration_with_monitoring(
    buffer: &CalibrationBuffer,
    old_kappa_sister: f64,
    old_kappa_anchor: f64,
    config: &PlattConfig,
    monitoring: &crate::config::types::MonitoringConfig,
) -> PlattRefitResult {
    if buffer.is_empty() {
        return PlattRefitResult {
            kappa_sister: old_kappa_sister,
            kappa_anchor: old_kappa_anchor,
            delta_cal: 0.0,
            sister_fitted: false,
            anchor_fitted: false,
            sister_effective_samples: 0.0,
            anchor_effective_samples: 0.0,
            discrimination: None,
        };
    }

    // ── Phase 1: Pre-scan ───────────────────────────────────────────
    let precomputed = precompute_weights(buffer, config.gamma_cal);

    // The floor is read against the undiscounted weighted counts
    // (´constr:platt:buffer´); the recency factor belongs to the
    // objective alone (´def:platt:objective´).
    let sister_counts = effective_sample_counts(buffer, RegimeSelector::Sister);
    let anchor_counts = effective_sample_counts(buffer, RegimeSelector::Anchor);

    // ── Phase 2: Per-regime golden section ──────────────────────────
    let sister_result = if sister_counts.meets_minimums(config) {
        Some(fit_single_regime(&precomputed, RegimeSelector::Sister, config))
    } else {
        None
    };

    let anchor_result = if anchor_counts.meets_minimums(config) {
        Some(fit_single_regime(&precomputed, RegimeSelector::Anchor, config))
    } else {
        None
    };

    // ── Phase 3: Post-fit assembly ──────────────────────────────────
    let kappa_sister = sister_result.unwrap_or(old_kappa_sister);
    let kappa_anchor = anchor_result.unwrap_or(old_kappa_anchor);

    let delta_sister = if sister_result.is_some() {
        (kappa_sister.ln() - old_kappa_sister.ln()).abs()
    } else {
        0.0
    };
    let delta_anchor = if anchor_result.is_some() {
        (kappa_anchor.ln() - old_kappa_anchor.ln()).abs()
    } else {
        0.0
    };

    // ── Phase 3b: Discrimination metrics (´dec:health:cached-discrimination´), at the post-fit
    // parameters so the coverage residuals are formed at the current
    // regime's calibration (´alg:monitoring:empirical-coverage´). The
    // AUC family reads only the rows and is unaffected by the move
    // from the pre-fit phase.
    let cal_rows: Vec<_> = buffer
        .iter()
        .map(|e| (e.rho_eff, e.positive, e.anchor_weight, e.uncertainty, e.axis_data.clone()))
        .collect();
    let discrimination = {
        let metrics = crate::health::compute_discrimination_metrics_with_monitoring(
            &cal_rows,
            kappa_sister,
            kappa_anchor,
            config.n_cal_min as usize,
            monitoring,
        );
        // Only keep if at least one AUC was computed
        if metrics.auc_aggregate.is_some() {
            Some(metrics)
        } else {
            None
        }
    };

    PlattRefitResult {
        kappa_sister,
        kappa_anchor,
        delta_cal: delta_sister.max(delta_anchor),
        sister_fitted: sister_result.is_some(),
        anchor_fitted: anchor_result.is_some(),
        sister_effective_samples: sister_counts.total,
        anchor_effective_samples: anchor_counts.total,
        discrimination,
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Phase 1: Pre-scan
// ═══════════════════════════════════════════════════════════════════════════════

/// Pre-computes per-entry combined weights for both regimes.
///
/// Iterates newest-first for numerically stable recency weighting.
/// Newest entry gets recency = 1.0; each step back multiplies by `γ_cal`.
///
/// The pre-scan is the fit's first phase (´alg:platt:fitting´).
fn precompute_weights(buffer: &CalibrationBuffer, gamma_cal: f64) -> Vec<PrecomputedEntry> {
    let n = buffer.len();
    let mut result = Vec::with_capacity(n);

    let mut recency = 1.0;
    for entry in buffer.iter().rev() {
        let g = regime_transition(entry.anchor_weight);

        result.push(PrecomputedEntry {
            rho: entry.rho_eff,
            positive: entry.positive,
            sister_weight: (1.0 - g) * entry.importance_weight * recency,
            anchor_weight: g * entry.importance_weight * recency,
        });

        recency *= gamma_cal;
    }

    // Reverse to restore oldest-first order (matches buffer).
    result.reverse();
    result
}

/// Computes a regime's effective sample counts: each record's regime
/// share times its importance weight, with no recency discount
/// (´constr:platt:buffer´).
fn effective_sample_counts(buffer: &CalibrationBuffer, regime: RegimeSelector) -> EffectiveCounts {
    let mut total = 0.0;
    let mut positive = 0.0;

    for entry in buffer.iter() {
        let g = regime_transition(entry.anchor_weight);
        let share = match regime {
            RegimeSelector::Sister => 1.0 - g,
            RegimeSelector::Anchor => g,
        };
        let w = share * entry.importance_weight;
        total += w;
        if entry.positive {
            positive += w;
        }
    }

    EffectiveCounts {
        total,
        positive,
        negative: total - positive,
    }
}

// ═══════════════════════════════════════════════════════════════════════════════
// Phase 2: Golden Section Search
// ═══════════════════════════════════════════════════════════════════════════════

/// Fits a single regime's κ via golden section search on log(κ).
///
/// The objective is the weighted binary cross-entropy loss. Golden
/// section search finds the minimum of a unimodal function on an
/// interval. The loss is unimodal in log(κ) for any non-degenerate
/// score distribution.
///
/// Returns the optimal κ value.
///
/// The per-regime search is the fit's second phase (´alg:platt:fitting´).
#[allow(clippy::suboptimal_flops)] // Justified: mul_add fuses the golden-section update's rounding and drifts Platt calibration against pinned regression oracles; the plain form is the calibrated arithmetic
fn fit_single_regime(entries: &[PrecomputedEntry], regime: RegimeSelector, config: &PlattConfig) -> f64 {
    let log_lo = config.kappa_min.ln();
    let log_hi = config.kappa_max.ln();

    // Golden ratio inverse: 1/φ = 2/(1+√5) ≈ 0.618
    let inv_phi = 2.0 / (1.0 + 5.0_f64.sqrt());

    let loss_at = |log_kappa: f64| -> f64 { regime_loss(entries, regime, log_kappa.exp()) };

    let mut a = log_lo;
    let mut b = log_hi;
    let mut x1 = b - inv_phi * (b - a);
    let mut x2 = a + inv_phi * (b - a);
    let mut f1 = loss_at(x1);
    let mut f2 = loss_at(x2);

    for _ in 0..config.max_golden_iterations {
        if (b - a).abs() < config.golden_tolerance {
            break;
        }
        if f1 < f2 {
            b = x2;
            x2 = x1;
            f2 = f1;
            x1 = b - inv_phi * (b - a);
            f1 = loss_at(x1);
        } else {
            a = x1;
            x1 = x2;
            f1 = f2;
            x2 = a + inv_phi * (b - a);
            f2 = loss_at(x2);
        }
    }

    f64::midpoint(a, b).exp()
}

/// Evaluates the weighted binary cross-entropy for one regime at a given κ.
///
/// Single pass over the buffer. Entries with combined weight < 10⁻²⁰
/// are skipped.
///
/// The per-regime search is the fit's second phase (´alg:platt:fitting´).
fn regime_loss(entries: &[PrecomputedEntry], regime: RegimeSelector, kappa: f64) -> f64 {
    let mut loss = 0.0;
    let inv_kappa = 1.0 / kappa;

    for e in entries {
        let w = match regime {
            RegimeSelector::Sister => e.sister_weight,
            RegimeSelector::Anchor => e.anchor_weight,
        };
        if w < 1e-20 {
            continue;
        }

        let p = sigmoid_clamped(e.rho * inv_kappa);

        let entry_loss = if e.positive { -p.ln() } else { -(1.0 - p).ln() };

        loss = w.mul_add(entry_loss, loss);
    }
    loss
}

// ═══════════════════════════════════════════════════════════════════════════════
// Numerical Utilities
// ═══════════════════════════════════════════════════════════════════════════════

/// Sigmoid with output clamping to prevent log(0).
///
/// Delegates to [`crate::numerics::stable_sigmoid`] for the core
/// two-branch computation, then clamps the output to `[ε, 1−ε]`
/// for log-loss stability.
///
/// The search's objective is the fit's second phase (´alg:platt:fitting´).
/// The package mandates one sigmoid definition and multiple imports of it —
/// this thin wrapper adds only the clamp.
fn sigmoid_clamped(x: f64) -> f64 {
    /// Clamping epsilon to prevent log(0).
    const EPS: f64 = 1e-15;

    crate::numerics::stable_sigmoid(x).clamp(EPS, 1.0 - EPS)
}

// ═══════════════════════════════════════════════════════════════════════════════
// Unit Tests
// ═══════════════════════════════════════════════════════════════════════════════

#[cfg(test)]
#[allow(clippy::cast_precision_loss, clippy::cast_lossless, clippy::suboptimal_flops)]
mod tests {
    use super::*;

    /// Helper: generate entries from a sigmoid model with known κ.
    ///
    /// Uses deterministic assignment: entry i is positive iff
    /// `σ`(`ρ_i` / `κ_true`) > `threshold_i`, where `threshold_i` is evenly spaced.
    fn make_calibrated_entries(true_kappa: f64, n: usize, anchor_weight: f64) -> CalibrationBuffer {
        let mut buffer = CalibrationBuffer::new(n);
        for i in 0..n {
            // Spread ρ values over a reasonable range
            let rho_eff = -5.0 + 10.0 * (i as f64) / (n as f64 - 1.0).max(1.0);
            let p_true = sigmoid_clamped(rho_eff / true_kappa);
            // Deterministic threshold: entry i is positive if p_true > (i % 10) / 10
            let threshold = ((i % 10) as f64) / 10.0;
            let is_positive = p_true > threshold;

            buffer.push(CalibrationEntry {
                rho_eff,
                uncertainty: 0.0,
                anchor_weight,
                positive: is_positive,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }
        buffer
    }

    /// The rungs of the overlap ladder: `(score, rows, positive rows)`.
    ///
    /// Eight rows stand at each of five scores and every rung carries both
    /// outcomes — one positive at the bottom, seven at the top, four in the
    /// middle — so the two classes overlap across the whole range instead of
    /// separating at some cut. The positive counts are antisymmetric about the
    /// middle rung, which balances a block at twenty positives to twenty
    /// negatives and drops the zero-score rung out of the stationarity
    /// condition below.
    const OVERLAP_LADDER: [(f64, usize, usize); 5] = [(-4.0, 8, 1), (-2.0, 8, 2), (0.0, 8, 4), (2.0, 8, 6), (4.0, 8, 7)];

    /// The κ minimising the overlap ladder's unweighted cross-entropy.
    ///
    /// This is not a reading taken from the search. Writing `u = 1/κ`, the
    /// derivative of the loss is `Σ_ℓ ρ_ℓ (N_ℓ σ(ρ_ℓ u) − n⁺_ℓ)`; the
    /// zero-score rung contributes nothing and the antisymmetric pairs
    /// collapse it to `2σ(4u) + σ(2u) = 5/2`, whose root is
    /// `u = 0.506_000_543_503_559_1`. This constant is that root's reciprocal.
    /// The second derivative is `Σ_ℓ ρ_ℓ² N_ℓ p_ℓ(1 − p_ℓ)`, strictly positive
    /// wherever any score is non-zero, so the loss is strictly convex in `u`
    /// and the root is the unique minimum rather than one stationary point
    /// among several.
    const OVERLAP_LADDER_KAPPA: f64 = 1.976_282_462_220_253;

    /// Builds a buffer holding `blocks` repetitions of the overlap ladder,
    /// every score multiplied by `scale`.
    ///
    /// The objective reads the scores only through the product `ρ/κ`, so
    /// multiplying every score by `s` moves the minimising κ to exactly
    /// `s · κ*`. That is how the drift scenario below displaces the fit by an
    /// amount settled in advance rather than one discovered by running it.
    ///
    /// Every row carries unit importance and one shared anchor weight, so the
    /// weights the fit computes differ only by the recency discount; with that
    /// discount switched off the per-row weights are one common factor, which
    /// scales the loss without moving its argument. Repeating the block
    /// therefore leaves the minimising κ where a single block put it.
    fn overlap_ladder_buffer(scale: f64, blocks: usize) -> CalibrationBuffer {
        let rows_per_block: usize = OVERLAP_LADDER.iter().map(|&(_, rows, _)| rows).sum();
        let mut buffer = CalibrationBuffer::new(blocks * rows_per_block);
        for _ in 0..blocks {
            for (rho, rows, positives) in OVERLAP_LADDER {
                for row in 0..rows {
                    buffer.push(CalibrationEntry {
                        rho_eff: rho * scale,
                        uncertainty: 0.0,
                        anchor_weight: 0.05,
                        positive: row < positives,
                        importance_weight: 1.0,
                        axis_data: vec![],
                    });
                }
            }
        }
        buffer
    }

    /// The configuration the ladder is fitted under: the shipped one with the
    /// recency discount switched off.
    ///
    /// Recency is what makes the fit track a moving population, and another
    /// test in this module holds it to that. Here it would only correlate the
    /// row weights with the order the rungs happen to be laid down in, which
    /// would displace the minimum away from the root the ladder's counts
    /// imply and leave the expectation unrecomputable by hand. At `γ_cal = 1`
    /// the objective is the plain unweighted cross-entropy of that root.
    fn overlap_ladder_config() -> PlattConfig {
        PlattConfig {
            gamma_cal: 1.0,
            ..PlattConfig::default()
        }
    }

    /// A refit with nothing to learn from returns the calibration it was given,
    /// unmoved: both constants come back as they went in, the reported movement is
    /// zero, neither regime is marked fitted and both effective sample counts are
    /// empty. A refit triggered before any labels have arrived is a no-op rather
    /// than a reset to whatever the fit's default would be.
    ///
    /// ´claim:risk:a-refit-with-an-empty-buffer-returns-the-existing-calibration-untouched´
    /// ´test:unit:empty-buffer-returns-old-kappa´
    #[test]
    fn empty_buffer_returns_old_kappa() {
        let buffer = CalibrationBuffer::new(100);
        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.5, 2.0, &config);

        assert!((result.kappa_sister - 1.5).abs() < f64::EPSILON);
        assert!((result.kappa_anchor - 2.0).abs() < f64::EPSILON);
        assert!(result.delta_cal.abs() < f64::EPSILON);
        assert!(!result.sister_fitted);
        assert!(!result.anchor_fitted);
        assert!(result.sister_effective_samples.abs() < f64::EPSILON);
        assert!(result.anchor_effective_samples.abs() < f64::EPSILON);
    }

    /// Given outcomes generated by a known calibration constant, the fit recovers
    /// that constant from a starting point well away from it. The search is
    /// therefore doing statistics rather than tracking its own initialisation: it
    /// finds the scaling that the data actually implies.
    ///
    /// ´claim:risk:the-fit-recovers-the-calibration-constant-that-generated-the-outcomes´
    /// ´test:unit:synthetic-convergence-kappa-2´
    #[test]
    fn synthetic_convergence_kappa_2() {
        // Generate entries from a model with true κ = 2.0.
        // Sister regime (low anchor weight), 10% positive rate.
        let buffer = make_calibrated_entries(2.0, 2_000, 0.05);
        let config = PlattConfig {
            n_cal_min: 30,
            n_cal_pos: 3,
            n_cal_neg: 3,
            ..PlattConfig::default()
        };

        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        assert!(result.sister_fitted, "sister regime should be fitted");
        // Recovered κ should be within search tolerance of 2.0
        assert!(
            (result.kappa_sister - 2.0).abs() < 0.15,
            "recovered κ_sister={:.4} should be near 2.0",
            result.kappa_sister
        );
    }

    /// One buffer holding entries from both regimes, each generated with its own
    /// calibration constant, yields two fits that both succeed and end up clearly
    /// apart. The regimes are fitted independently, so a sister-dominated score and
    /// an anchor-dominated one are not forced to share a scaling that suits neither.
    ///
    /// ´claim:risk:the-two-regimes-are-fitted-independently-so-they-can-settle-on-different-constants´
    /// ´test:unit:regime-separation´
    #[test]
    fn regime_separation() {
        // Buffer with entries in two distinct regimes:
        // w < 0.1 (sister-dominated) and w > 0.7 (anchor-dominated)
        let mut buffer = CalibrationBuffer::new(2_000);

        // Sister regime: κ_true ≈ 1.5
        for i in 0..500 {
            let rho = -3.0 + 6.0 * (i as f64) / 499.0;
            let p = sigmoid_clamped(rho / 1.5);
            let threshold = ((i % 10) as f64) / 10.0;
            buffer.push(CalibrationEntry {
                rho_eff: rho,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: p > threshold,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        // Anchor regime: κ_true ≈ 3.0
        for i in 0..500 {
            let rho = -3.0 + 6.0 * (i as f64) / 499.0;
            let p = sigmoid_clamped(rho / 3.0);
            let threshold = ((i % 10) as f64) / 10.0;
            buffer.push(CalibrationEntry {
                rho_eff: rho,
                uncertainty: 0.0,
                anchor_weight: 0.80,
                positive: p > threshold,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        assert!(result.sister_fitted, "sister should be fitted");
        assert!(result.anchor_fitted, "anchor should be fitted");
        // The two κ values should be different (regime separation)
        assert!(
            (result.kappa_sister - result.kappa_anchor).abs() > 0.3,
            "κ_sister={:.4} and κ_anchor={:.4} should differ significantly",
            result.kappa_sister,
            result.kappa_anchor
        );
    }

    /// Plenty of entries is not the same as enough of each outcome. A regime with
    /// fifty negatives but only two positives is left unfitted and keeps its previous
    /// constant, because the minimum is enforced on the positive and negative counts
    /// separately. Fitting a sigmoid to data that is one-sided would push the constant
    /// to a bound on the strength of two labels.
    ///
    /// ´claim:risk:a-regime-short-of-its-per-outcome-minimums-is-not-refitted-and-keeps-its-previous-constant´
    /// ´test:unit:minimum-sample-guard´
    #[test]
    fn minimum_sample_guard() {
        // A regime with only 2 positive entries should not be fitted.
        let mut buffer = CalibrationBuffer::new(100);

        // Only 2 positive entries (below n_cal_pos=3)
        buffer.push(CalibrationEntry {
            rho_eff: 1.0,
            uncertainty: 0.0,
            anchor_weight: 0.05,
            positive: true,
            importance_weight: 1.0,
            axis_data: vec![],
        });
        buffer.push(CalibrationEntry {
            rho_eff: 0.5,
            uncertainty: 0.0,
            anchor_weight: 0.05,
            positive: true,
            importance_weight: 1.0,
            axis_data: vec![],
        });
        for i in 0..50 {
            buffer.push(CalibrationEntry {
                rho_eff: -1.0 + 0.02 * i as f64,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: false,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.5, 1.0, &config);

        // Sister regime should NOT be fitted (only ~2 weighted positives)
        assert!(!result.sister_fitted, "sister should not be fitted with only 2 positives");
        assert!(
            (result.kappa_sister - 1.5).abs() < f64::EPSILON,
            "κ_sister should retain old value 1.5"
        );
    }

    /// When every score in the buffer is identical the loss surface carries no
    /// information about the scaling, and the search still terminates with a finite,
    /// positive constant inside its bounds — it drifts to a boundary rather than
    /// diverging or returning something unusable. A stub-valued or saturated period
    /// leaves calibration harmlessly inert instead of breaking it.
    ///
    /// ´claim:risk:a-degenerate-score-distribution-still-terminates-with-a-finite-positive-constant´
    /// ´test:unit:stub-valued-entries-converge´
    #[test]
    fn stub_valued_entries_converge() {
        // Buffer filled with constant ρ̂_eff=0.2 → search converges,
        // finite κ, δ_cal ≈ 0 (mechanism inert when all scores identical).
        let mut buffer = CalibrationBuffer::new(200);
        for i in 0..200 {
            buffer.push(CalibrationEntry {
                rho_eff: 0.2,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: i % 5 == 0, // 20% positive rate
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        assert!(result.sister_fitted);
        assert!(result.kappa_sister.is_finite(), "κ should be finite");
        assert!(result.kappa_sister > 0.0, "κ should be positive");
        // With constant ρ the loss surface is degenerate — the search converges
        // to a boundary, so δ_cal can be large.  The meaningful guarantee is
        // that the search terminates with a finite, positive κ inside bounds.
        assert!(
            result.kappa_sister >= 0.01 && result.kappa_sister <= 100.0,
            "κ_sister={:.4} should be within search bounds",
            result.kappa_sister
        );
    }

    /// A buffer of zero scores is worse than uninformative — it is silent. Every
    /// candidate sharpness predicts a half for every row, so the cross-entropy is
    /// one constant across the whole search range, and what comes back is not a
    /// fit but the bound the iteration walks to while every comparison it makes
    /// is a tie. Two buffers sharing nothing else — different lengths, different
    /// base rates, different importance — return the same sharpness bit for bit,
    /// and the drift between them is not small but exactly nothing. That is what
    /// makes a drift bound applied to such a pair vacuous: it is not that the
    /// calibration held steady, it is that no calibration was performed, and the
    /// bound would pass at any width whatever. The neighbouring tests fit a
    /// fixture whose classes overlap for exactly this reason
    /// (´tab:assayer:harness-scenario-tolerances´).
    ///
    /// ´claim:risk:a-buffer-of-zero-scores-returns-the-same-bound-bit-for-bit-so-a-drift-bound-over-such-refits-is-vacuous´
    /// ´test:unit:flat-scores-leave-successive-refits-bit-identical´
    #[test]
    fn flat_scores_leave_successive_refits_bit_identical() {
        /// Builds a buffer whose every score is zero.
        fn flat(rows: usize, one_positive_in: usize, importance: f64) -> CalibrationBuffer {
            let mut buffer = CalibrationBuffer::new(rows);
            for row in 0..rows {
                buffer.push(CalibrationEntry {
                    rho_eff: 0.0,
                    uncertainty: 0.0,
                    anchor_weight: 0.05,
                    positive: row % one_positive_in == 0,
                    importance_weight: importance,
                    axis_data: vec![],
                });
            }
            buffer
        }

        let config = PlattConfig::default();
        let first = refit_platt_calibration(&flat(100, 2, 1.0), 1.0, 1.0, &config);
        let second = refit_platt_calibration(&flat(400, 4, 2.5), 1.0, 1.0, &config);

        assert!(
            first.sister_fitted && second.sister_fitted,
            "both buffers clear the sample floor"
        );

        // Bit-identical, not merely close: the two populations have no figure
        // in common, and the search never consulted them.
        crate::testing::assert_near(
            first.kappa_sister,
            second.kappa_sister,
            crate::testing::DEFAULT_TOLERANCES.bit_identical,
            "sharpness fitted to two unrelated buffers of zero scores",
        );

        // And what they agree on is the ceiling, short of it only by the half
        // of the final bracket the search stops on.
        assert!(
            config.kappa_max - first.kappa_sister < 0.01,
            "the returned sharpness {} should be the search's ceiling artefact, not an optimum",
            first.kappa_sister,
        );

        // So the declared drift bound admits this pair while deciding nothing.
        assert!(
            (first.kappa_sister.ln() - second.kappa_sister.ln()).abs() <= crate::testing::DEFAULT_TOLERANCES.platt_log_sharpness,
            "the vacuity is the point: the bound passes because the difference is identically zero",
        );
    }

    /// Classes whose scores genuinely overlap put the fit at an interior optimum
    /// rather than against a search bound: the overlap ladder's fitted constant
    /// lands on the root of the stationarity condition its own counts imply, and
    /// sits some four units of log-κ clear of either end of the search range. The
    /// preceding test is the contrast that gives this one its point — a buffer
    /// whose scores carry no information leaves the search resting on a bound,
    /// where the returned constant is an artefact of how the iteration breaks a
    /// tie and no later assertion about it can discriminate anything. An interior
    /// optimum is what makes the fitted constant a statement about the data, and
    /// it is the precondition the search's own unimodality argument rests on.
    ///
    /// ´claim:risk:overlapping-score-classes-put-the-fit-at-an-interior-optimum-rather-than-against-a-search-bound´
    /// ´test:unit:overlap-ladder-fit-lands-at-the-interior-optimum´
    #[test]
    fn overlap_ladder_fit_lands_at_the_interior_optimum() {
        let buffer = overlap_ladder_buffer(1.0, 2);
        let config = overlap_ladder_config();

        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        assert!(result.sister_fitted, "the ladder clears the sister regime's sample floor");

        // The search resolves log-κ only to its own golden tolerance, so the
        // constant it returns sits within about half that of the hand-derived
        // root — the band below is that resolution with room to spare, and is
        // far tighter than the distance to either bound.
        assert!(
            (result.kappa_sister - OVERLAP_LADDER_KAPPA).abs() < 1e-3,
            "fitted κ_sister={} should sit on the stationarity root {OVERLAP_LADDER_KAPPA}",
            result.kappa_sister,
        );

        // Interior by a margin, stated in the coordinate the search works in.
        let margin = (result.kappa_sister.ln() - config.kappa_min.ln()).min(config.kappa_max.ln() - result.kappa_sister.ln());
        assert!(
            margin > 3.0,
            "fitted κ_sister={} should stand clear of both search bounds; margin in log-κ was {margin}",
            result.kappa_sister,
        );
    }

    /// Multiplying every score by a factor multiplies the fitted constant by that
    /// same factor, which is what makes the declared drift bound a two-sided
    /// assertion: a four-percent perturbation of the scores moves the constant
    /// and stays inside the bound, while a ten-percent one moves it past and the
    /// bound rejects it. Both halves are asserted because a bound that only ever
    /// sees movement it admits is indistinguishable from a bound that admits
    /// everything — the rejecting case is what shows the figure is deciding
    /// something (´tab:assayer:harness-scenario-tolerances´).
    ///
    /// ´claim:risk:scaling-every-score-scales-the-fitted-constant-alike-so-the-drift-bound-admits-the-small-move-and-rejects-the-large´
    /// ´test:unit:overlap-ladder-drift-bound-admits-and-rejects´
    #[test]
    fn overlap_ladder_drift_bound_admits_and_rejects() {
        /// The perturbation the bound is meant to admit.
        const SMALL: f64 = 1.04;
        /// The perturbation the bound is meant to reject.
        const LARGE: f64 = 1.10;

        let config = overlap_ladder_config();
        let fit = |scale: f64| refit_platt_calibration(&overlap_ladder_buffer(scale, 2), 1.0, 1.0, &config).kappa_sister;

        let base = fit(1.0);
        let small = fit(SMALL);
        let large = fit(LARGE);

        // The proportionality itself, before either bound is consulted.
        assert!(
            (small - SMALL * base).abs() < 1e-3,
            "a {SMALL}× score scaling should carry κ from {base} to {}, but the fit gave {small}",
            SMALL * base,
        );
        assert!(
            (large - LARGE * base).abs() < 1e-3,
            "a {LARGE}× score scaling should carry κ from {base} to {}, but the fit gave {large}",
            LARGE * base,
        );

        // The comparison is in log-sharpness, so what the bound sees is the
        // proportion the sharpness moved by and not the distance it moved.
        // That is what makes this pair of stimuli a test of the bound rather
        // than of the fixture: a scaling by a factor is the same proportional
        // move at every sharpness, so the same four-percent and ten-percent
        // perturbations would be admitted and rejected at any optimum, and not
        // only near this ladder's own (´tab:assayer:harness-scenario-tolerances´).
        let bound = crate::testing::DEFAULT_TOLERANCES.platt_log_sharpness;

        // Green: the perturbed refit moved, and moved by less than the bound.
        let admitted = (small.ln() - base.ln()).abs();
        assert!(
            admitted > 0.0,
            "the perturbed refit must actually move, else the bound decides nothing",
        );
        assert!(
            admitted <= bound,
            "a {SMALL}× perturbation should stay inside the declared drift bound: κ went {base} → {small} \
             (|Δ ln κ| = {admitted}, bound {bound})",
        );

        // Red: the deliberate violation is caught.
        let rejected = (large.ln() - base.ln()).abs();
        assert!(
            rejected > bound,
            "a {LARGE}× perturbation should breach the declared drift bound: κ went {base} → {large} \
             (|Δ ln κ| = {rejected}, bound {bound})",
        );
    }

    /// A fitted constant never leaves the configured search interval, even when the
    /// data was generated by a constant near its lower end. The search brackets the
    /// whole of log-space between the two bounds and can only ever narrow inwards,
    /// so the operator's limits are a guarantee about the output and not merely a
    /// starting hint.
    ///
    /// ´claim:risk:a-fitted-constant-never-leaves-the-configured-search-interval´
    /// ´test:unit:search-within-bounds´
    #[test]
    fn search_within_bounds() {
        // Fitted κ should always be in [0.01, 100].
        let buffer = make_calibrated_entries(0.5, 500, 0.05);
        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        if result.sister_fitted {
            assert!(
                result.kappa_sister >= config.kappa_min && result.kappa_sister <= config.kappa_max,
                "κ_sister={:.6} should be in [{}, {}]",
                result.kappa_sister,
                config.kappa_min,
                config.kappa_max
            );
        }
    }

    /// The cross-entropy stays finite across the whole search range even for scores
    /// far outside anything the model would ordinarily produce, including a
    /// confidently wrong one. The loss takes a logarithm of the predicted
    /// probability, so a single saturated score would otherwise contribute an
    /// infinity and make every candidate constant look equally bad.
    ///
    /// ´claim:risk:the-cross-entropy-stays-finite-at-extreme-scores-across-the-whole-search-range´
    /// ´test:unit:no-nan-in-loss´
    #[test]
    fn no_nan_in_loss() {
        // Sweep κ from 0.01 to 100 and ρ from −100 to 100 — no NaN.
        let entries = vec![
            PrecomputedEntry {
                rho: 100.0,
                positive: true,
                sister_weight: 1.0,
                anchor_weight: 0.01,
            },
            PrecomputedEntry {
                rho: -100.0,
                positive: false,
                sister_weight: 1.0,
                anchor_weight: 0.01,
            },
            PrecomputedEntry {
                rho: 0.0,
                positive: true,
                sister_weight: 1.0,
                anchor_weight: 0.01,
            },
        ];

        for log_k in -4..=5 {
            let kappa = (log_k as f64).exp();
            let loss = regime_loss(&entries, RegimeSelector::Sister, kappa);
            assert!(loss.is_finite(), "loss should be finite at κ={kappa:.4}");
            assert!(!loss.is_nan(), "loss should not be NaN at κ={kappa:.4}");
        }
    }

    /// This is why: the calibration sigmoid is held strictly inside the unit
    /// interval, at scores of a thousand in either direction as much as at zero.
    /// Neither endpoint is ever returned, so the logarithm the loss takes of it and
    /// of its complement always has an argument.
    ///
    /// ´claim:risk:the-calibration-sigmoid-never-returns-exactly-zero-or-one´
    /// ´test:unit:sigmoid-clamped-never-zero-or-one´
    #[test]
    fn sigmoid_clamped_never_zero_or_one() {
        let eps = 1e-15;
        for x in [-1000.0, -100.0, -10.0, 0.0, 10.0, 100.0, 1000.0] {
            let p = sigmoid_clamped(x);
            assert!(p >= eps, "sigmoid_clamped({x}) = {p} should be >= {eps}");
            assert!(p <= 1.0 - eps, "sigmoid_clamped({x}) = {p} should be <= {}", 1.0 - eps);
        }
    }

    /// The recency discount is anchored at the newest entry, which carries full
    /// weight, with each older one worth a fixed fraction more of the discount — so
    /// the newest entry in a buffer outweighs the oldest. Anchoring at the newest
    /// rather than the oldest keeps the weights bounded by one however long the
    /// buffer has been running.
    ///
    /// ´claim:risk:recency-weighting-gives-the-newest-entry-full-weight-and-discounts-each-older-one´
    /// ´test:unit:precompute-newest-first-recency´
    #[test]
    fn precompute_newest_first_recency() {
        let mut buffer = CalibrationBuffer::new(10);
        for i in 0..5 {
            buffer.push(CalibrationEntry {
                rho_eff: i as f64,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: true,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        let precomputed = precompute_weights(&buffer, 0.9998);

        // After reverse, index 0 = oldest, index 4 = newest.
        // Newest should have highest sister_weight (recency=1.0).
        // Oldest should have lowest (recency = 0.9998^4).
        assert!(
            precomputed[4].sister_weight > precomputed[0].sister_weight,
            "newest entry should have higher weight than oldest"
        );
    }

    /// The calibration buffer is bounded and drops from the front: pushing beyond
    /// capacity leaves exactly the most recent entries, in order. Memory is therefore
    /// fixed however long the instance runs, and what is sacrificed for that is
    /// always the oldest evidence — the evidence recency weighting was already
    /// discounting most heavily.
    ///
    /// ´claim:risk:the-calibration-buffer-at-capacity-drops-its-oldest-entry-to-admit-a-new-one´
    /// ´test:unit:buffer-push-evicts-oldest´
    #[test]
    fn buffer_push_evicts_oldest() {
        let mut buffer = CalibrationBuffer::new(3);
        for i in 0..5 {
            buffer.push(CalibrationEntry {
                rho_eff: i as f64,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: true,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        assert_eq!(buffer.len(), 3);
        // Oldest two (0, 1) should be evicted; remaining: 2, 3, 4
        let entries: Vec<_> = buffer.iter().collect();
        assert!((entries[0].rho_eff - 2.0).abs() < f64::EPSILON);
        assert!((entries[1].rho_eff - 3.0).abs() < f64::EPSILON);
        assert!((entries[2].rho_eff - 4.0).abs() < f64::EPSILON);
    }

    /// How far the calibration moved is measured as the absolute difference of the
    /// logarithms, not of the constants themselves. Movement is therefore relative: a
    /// step from one to two counts the same as a step from ten to twenty, which is
    /// what a downstream threshold on "the calibration has shifted" needs, since the
    /// constant is a scaling.
    ///
    /// ´claim:risk:calibration-movement-is-measured-as-a-log-ratio-so-it-is-relative-not-absolute´
    /// ´test:unit:delta-cal-log-space´
    #[test]
    fn delta_cal_log_space() {
        // When κ_old=1.0 and κ_new=2.0, δ_cal should be |ln(2) - ln(1)| = ln(2)
        let mut buffer = CalibrationBuffer::new(200);
        for i in 0..200 {
            let rho = -5.0 + 10.0 * (i as f64) / 199.0;
            let p = sigmoid_clamped(rho / 2.0);
            let threshold = ((i % 10) as f64) / 10.0;
            buffer.push(CalibrationEntry {
                rho_eff: rho,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: p > threshold,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        if result.sister_fitted {
            // δ_cal should be in log space
            let expected_delta = (result.kappa_sister.ln() - 1.0_f64.ln()).abs();
            assert!(
                (result.delta_cal - expected_delta).abs() < 1e-10,
                "δ_cal should be computed in log space"
            );
        }
    }

    /// A tolerance so tight that floating-point arithmetic can never satisfy it does
    /// not hang the search: the iteration cap ends it and a finite constant comes
    /// back. The refit runs on the model owner's thread, so a convergence criterion
    /// that cannot be met has to cost a bounded number of iterations rather than the
    /// instance.
    ///
    /// ´claim:risk:the-iteration-cap-ends-the-search-even-when-the-tolerance-can-never-be-met´
    /// ´test:unit:golden-section-terminates´
    #[test]
    fn golden_section_terminates() {
        // Verify the golden section search always terminates within max iterations.
        // Use a very tight tolerance to force max iterations.
        let buffer = make_calibrated_entries(1.0, 100, 0.05);
        let config = PlattConfig {
            golden_tolerance: 1e-20, // Extremely tight
            max_golden_iterations: 50,
            ..PlattConfig::default()
        };

        // This should not hang — the iteration cap prevents infinite loops.
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);
        assert!(result.kappa_sister.is_finite());
    }

    /// A refit that actually fitted the anchor regime is recorded against the label
    /// count at which it happened, moving the tracker's stamp off its initial zero.
    /// The reactivation trigger measures how long the anchor has gone unfitted from
    /// that stamp, so a refit that succeeded but was not recorded would make the
    /// anchor look permanently overdue.
    ///
    /// ´claim:risk:a-successful-anchor-refit-is-stamped-with-the-label-index-it-happened-at´
    /// ´test:unit:anchor-refit-label-index-updated´
    #[test]
    fn anchor_refit_label_index_updated() {
        // When anchor is fitted, PlattConvergenceTracker should update
        // `last_anchor_refit_label_index` to the current label index.
        use crate::health::PlattConvergenceTracker;

        let mut buffer = CalibrationBuffer::new(2_000);

        // Build a buffer with enough anchor-regime entries to be fitted.
        for i in 0..500 {
            let rho = -3.0 + 6.0 * (i as f64) / 499.0;
            let p = sigmoid_clamped(rho / 2.0);
            let threshold = ((i % 10) as f64) / 10.0;
            buffer.push(CalibrationEntry {
                rho_eff: rho,
                uncertainty: 0.0,
                anchor_weight: 0.80,
                positive: p > threshold,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);
        assert!(result.anchor_fitted, "anchor should be fitted");

        let mut tracker = PlattConvergenceTracker::new();
        assert_eq!(tracker.last_anchor_refit_label_index, 0);

        tracker.record_refit(&result, 500);
        assert_eq!(
            tracker.last_anchor_refit_label_index, 500,
            "anchor refit label index should be updated to current label count"
        );
    }

    /// Calibration and blending divide the regimes with one shared transition
    /// function, agreeing exactly across the weight range rather than approximately.
    /// Two copies that drifted apart would mean an entity was blended as one regime
    /// and calibrated as another, and the mismatch would show up only as a
    /// mis-calibrated probability with nothing pointing at its cause.
    ///
    /// ´claim:risk:calibration-and-blending-split-the-regimes-with-one-shared-transition-function´
    /// ´test:unit:regime-transition-shared-with-blend´
    #[test]
    fn regime_transition_shared_with_blend() {
        // `regime_transition()` used in pre-scan must be the same function
        // used by the blend weight (´dec:calibration:shared-transition´).
        // Both import from `crate::numerics`.
        // Verify behaviour at key points matches the shared definition.
        use crate::numerics::regime_transition as shared_rt;

        for w in [0.0, 0.1, 0.3, 0.5, 0.8, 1.0] {
            let from_calibration = regime_transition(w);
            let from_shared = shared_rt(w);
            assert!(
                (from_calibration - from_shared).abs() < f64::EPSILON,
                "regime_transition({w}) differs: calibration={from_calibration}, shared={from_shared}"
            );
        }
    }

    /// The reported movement is large enough to be acted on when the calibration
    /// genuinely moves: data generated by a constant three times the one in force
    /// produces movement past the default drift-reset threshold. The threshold is
    /// therefore reachable by an ordinary recalibration, not a bar only a pathological
    /// one could clear.
    ///
    /// ´claim:risk:a-calibration-that-genuinely-moves-reports-movement-past-the-drift-reset-threshold´
    /// ´test:unit:delta-cal-exceeds-threshold´
    #[test]
    fn delta_cal_exceeds_threshold() {
        // When old κ=1.0 and recovered κ deviates, δ_cal should exceed
        // the drift-reset threshold (0.1) for sufficiently different κ.
        let buffer = make_calibrated_entries(3.0, 500, 0.05);
        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        assert!(result.sister_fitted, "sister should be fitted");
        assert!(
            result.delta_cal > config.delta_cal_threshold,
            "δ_cal={:.4} should exceed threshold={:.4} when κ moves from 1.0 to ~3.0",
            result.delta_cal,
            config.delta_cal_threshold
        );
    }

    /// The cheap pre-check admits a buffer that a real fit would accept: a hundred
    /// anchor-dominated entries carrying both outcomes clears the minimums. This scan
    /// is what decides whether a reactivation refit is worth running at all, so it has
    /// to say yes when the anchor really could be fitted.
    ///
    /// ´claim:risk:a-buffer-of-anchor-regime-entries-with-both-outcomes-clears-the-anchor-sufficiency-check´
    /// ´test:unit:has-sufficient-anchor-samples-true´
    #[test]
    fn has_sufficient_anchor_samples_true() {
        let mut buffer = CalibrationBuffer::new(200);
        // 100 entries with high anchor weight (regime_transition(0.8) ≈ 1.0)
        for i in 0..100 {
            buffer.push(CalibrationEntry {
                rho_eff: (i as f64) * 0.1 - 5.0,
                uncertainty: 0.0,
                anchor_weight: 0.80,
                positive: i % 5 == 0, // 20% positive
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }
        let config = PlattConfig::default();
        assert!(
            buffer.has_sufficient_anchor_samples(&config),
            "100 anchor-regime entries with 20% positive should be sufficient"
        );
    }

    /// The check counts each entry by its regime rather than by its existence, so
    /// fifty sister-dominated entries contribute almost nothing toward the anchor's
    /// minimums and the answer is no. Counting entries outright would report a busy
    /// sister-regime instance as having anchor evidence it has never gathered.
    ///
    /// ´claim:risk:sister-regime-entries-count-for-almost-nothing-toward-the-anchors-sample-requirement´
    /// ´test:unit:has-sufficient-anchor-samples-false´
    #[test]
    fn has_sufficient_anchor_samples_false() {
        let mut buffer = CalibrationBuffer::new(200);
        // Entries with low anchor weight (regime_transition(0.05) ≈ 0.007).
        // Effective anchor weight ≈ 0.007 per entry. 50 entries → ~0.35 total.
        // Well below n_cal_min=30.
        for i in 0..50 {
            buffer.push(CalibrationEntry {
                rho_eff: (i as f64) * 0.1,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: i % 5 == 0,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }
        let config = PlattConfig::default();
        assert!(
            !buffer.has_sufficient_anchor_samples(&config),
            "50 sister-regime entries should not have sufficient anchor samples"
        );
    }

    /// The sample floor reads the undiscounted weighted count — the same
    /// quantity the cheap pre-check computes — so an anchor regime whose
    /// evidence is old but sufficient is fitted rather than abandoned. Under
    /// a recency-discounted floor the same buffer sits in a trap: the
    /// pre-check keeps saying refit, the fit keeps refusing, the refit
    /// bookkeeping never advances, and a full search runs on every label.
    /// Recency belongs to the objective, which tracks the current score
    /// distribution; the floor is an evidence census and takes no discount.
    ///
    /// ´claim:risk:the-sample-floor-reads-the-undiscounted-weighted-count-the-pre-check-computes´
    /// ´test:unit:sample-floor-reads-undiscounted-count´
    #[test]
    fn sample_floor_reads_undiscounted_count() {
        let config = PlattConfig::default();
        let mut buffer = CalibrationBuffer::new(2_000);

        // 31 anchor-regime records first, i.e. oldest, with both outcomes
        // present. With the sister entries' small anchor share the
        // undiscounted anchor census is ≈ 38, above n_cal_min = 30.
        for i in 0..31 {
            buffer.push(CalibrationEntry {
                rho_eff: f64::from(i).mul_add(0.1, -1.5),
                uncertainty: 0.0,
                anchor_weight: 0.95,
                positive: i % 4 == 0,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }
        // 1,969 newer sister-regime records push the anchor block ~2,000
        // ranks back: at γ_cal = 0.9998 its recency factor is ≈ 0.67, so a
        // discounted census would read ≈ 27 and refuse the floor.
        for i in 0..1_969 {
            buffer.push(CalibrationEntry {
                rho_eff: f64::from(i % 40).mul_add(0.05, -1.0),
                uncertainty: 0.0,
                anchor_weight: 0.02,
                positive: i % 5 == 0,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        // The pre-check and the floor read the same census.
        assert!(buffer.has_sufficient_anchor_samples(&config));

        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);
        assert!(
            result.anchor_fitted,
            "anchor floor must read the undiscounted count, not the recency-discounted one"
        );

        // Independent recomputation of the undiscounted census: the anchor
        // block plus the sister entries' small anchor share. Discounting the
        // old anchor block by its ≈0.67 recency would read below the floor.
        let expected = 31.0_f64.mul_add(
            crate::numerics::regime_transition(0.95),
            1_969.0 * crate::numerics::regime_transition(0.02),
        );
        assert!(
            (result.anchor_effective_samples - expected).abs() < 1e-9,
            "reported anchor samples should be the undiscounted census {expected}, got {}",
            result.anchor_effective_samples
        );
    }

    /// The published regime counts are weighted samples, not a census against
    /// a hard threshold: a buffer whose entries all sit just below the old
    /// 0.3 split still reports substantial anchor evidence, because each
    /// record enters the anchor count at its transition share times its
    /// importance weight. A threshold tally would have reported zero anchor
    /// evidence here — and, through the risk basis, no anchor maturity —
    /// while the fit's own floor read a weighted count near half the buffer.
    ///
    /// ´claim:risk:the-snapshots-regime-counts-are-the-weighted-samples-the-sample-floor-reads´
    /// ´test:unit:snapshot-counts-weighted-below-threshold´
    #[test]
    fn snapshot_counts_weighted_below_threshold() {
        let mut buffer = CalibrationBuffer::new(50);
        // Every entry just below the regime boundary: g(0.29) = σ(20·(−0.01)).
        for i in 0..20 {
            buffer.push(CalibrationEntry {
                rho_eff: (i as f64).mul_add(0.1, -1.0),
                uncertainty: 0.0,
                anchor_weight: 0.29,
                positive: i % 4 == 0,
                importance_weight: 2.0,
                axis_data: vec![],
            });
        }
        let snapshot = buffer.to_snapshot();

        // Independent recomputation of the specified counts.
        let g = crate::numerics::regime_transition(0.29);
        let expected_anchor = 20.0 * 2.0 * g;
        let expected_sister = 20.0 * 2.0 * (1.0 - g);
        assert!((snapshot.anchor_regime_records - expected_anchor).abs() < 1e-9);
        assert!((snapshot.sister_regime_records - expected_sister).abs() < 1e-9);

        // The divergence the weighted count repairs: the anchor evidence is
        // substantial, where the threshold tally reported none at all.
        assert!(snapshot.anchor_regime_records > 15.0);
        assert_eq!(snapshot.total_entries, 20);
    }

    /// The calibration sigmoid is the crate's shared stable sigmoid with a clamp
    /// applied, matching it exactly wherever the clamp is not binding. There is one
    /// definition of the logistic curve in the package and calibration adds only the
    /// log-loss guard on top — a second implementation would eventually disagree with
    /// the one deciding probabilities on the assessment path.
    ///
    /// ´claim:risk:the-calibration-sigmoid-is-the-shared-stable-sigmoid-plus-a-clamp-not-a-second-implementation´
    /// ´test:unit:sigmoid-clamped-matches-stable-sigmoid´
    #[test]
    fn sigmoid_clamped_matches_stable_sigmoid() {
        // Verify sigmoid_clamped composes from stable_sigmoid (not a separate impl).
        use crate::numerics::stable_sigmoid;

        let eps = 1e-15;
        for x in [-100.0, -10.0, -1.0, 0.0, 1.0, 10.0, 100.0] {
            let clamped = sigmoid_clamped(x);
            let expected = stable_sigmoid(x).clamp(eps, 1.0 - eps);
            assert!(
                (clamped - expected).abs() < f64::EPSILON,
                "sigmoid_clamped({x}) = {clamped} != stable_sigmoid({x}).clamp() = {expected}"
            );
        }
    }

    /// Every iteration of the search strictly narrows the bracket, on real
    /// weighted data and in both of the branches the comparison can take. Because the
    /// interval only ever shrinks, the loop's progress toward its tolerance is
    /// guaranteed by the step itself rather than by the iteration cap catching a
    /// search that had stalled.
    ///
    /// ´claim:risk:every-golden-section-iteration-strictly-narrows-the-bracket´
    /// ´test:unit:golden-section-monotonicity´
    #[test]
    fn golden_section_monotonicity() {
        // The interval (b − a) must shrink every iteration.
        let buffer = make_calibrated_entries(2.0, 500, 0.05);
        let config = PlattConfig::default();
        let precomputed = precompute_weights(&buffer, config.gamma_cal);

        let log_lo = config.kappa_min.ln();
        let log_hi = config.kappa_max.ln();
        let inv_phi = 2.0 / (1.0 + 5.0_f64.sqrt());

        let loss_at = |log_kappa: f64| -> f64 { regime_loss(&precomputed, RegimeSelector::Sister, log_kappa.exp()) };

        let mut a = log_lo;
        let mut b = log_hi;
        let mut x1 = b - inv_phi * (b - a);
        let mut x2 = a + inv_phi * (b - a);
        let mut f1 = loss_at(x1);
        let mut f2 = loss_at(x2);
        let mut prev_width = b - a;

        for _ in 0..config.max_golden_iterations {
            if (b - a).abs() < config.golden_tolerance {
                break;
            }
            if f1 < f2 {
                b = x2;
                x2 = x1;
                f2 = f1;
                x1 = b - inv_phi * (b - a);
                f1 = loss_at(x1);
            } else {
                a = x1;
                x1 = x2;
                f1 = f2;
                x2 = a + inv_phi * (b - a);
                f2 = loss_at(x2);
            }
            let width = b - a;
            assert!(width < prev_width, "interval must shrink: {prev_width:.6} → {width:.6}");
            prev_width = width;
        }
    }

    /// Data that is adverse wherever the score is high and benign where it is very
    /// low drives the constant toward the steep end of its range, because the
    /// sharpest sigmoid is the one that best reproduces such a clean separation.
    /// The search leaning on a bound is the correct answer for near-separable data
    /// rather than a failure to converge.
    ///
    /// ´claim:risk:near-separable-outcomes-drive-the-constant-to-the-steep-end-of-its-range´
    /// ´test:unit:boundary-convergence-all-positive´
    #[test]
    fn boundary_convergence_all_positive() {
        // All-positive entries with ρ > 0 should push κ
        // toward kappa_min. The steepest sigmoid (smallest κ) best
        // separates "always positive" from the loss function.
        let mut buffer = CalibrationBuffer::new(500);
        for i in 0..500 {
            buffer.push(CalibrationEntry {
                rho_eff: 0.5 + 5.0 * (i as f64) / 499.0,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: true,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }
        // Need at least 3 negatives to meet minimum sample requirements.
        for _ in 0..5 {
            buffer.push(CalibrationEntry {
                rho_eff: -5.0,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: false,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        assert!(result.sister_fitted);
        // κ should be near the lower search bound — the best fit for
        // overwhelmingly positive high-ρ data is the steepest sigmoid.
        assert!(
            result.kappa_sister < 0.5,
            "κ_sister={:.4} should approach kappa_min={} for all-positive ρ>0 data",
            result.kappa_sister,
            config.kappa_min
        );
    }

    /// When the older and newer halves of the buffer were generated by different
    /// calibrations, the fit follows the newer one — landing well past the geometric
    /// midpoint the two halves would give if they counted equally. Recency weighting
    /// is what makes calibration track a shifting population instead of averaging
    /// over its whole history.
    ///
    /// ´claim:risk:when-the-old-and-new-halves-of-the-buffer-disagree-the-fit-follows-the-newer-one´
    /// ´test:unit:recency-weighting-dominance´
    #[test]
    fn recency_weighting_dominance() {
        // When old entries suggest κ ≈ 1 and new entries
        // suggest κ ≈ 5, the fit should be pulled toward 5.
        //
        // Use γ_cal = 0.99 (aggressive) so the effect is pronounced.
        // At the default 0.9998 the oldest entry still retains ~67% of
        // the newest's weight — too gentle for a clear dominance test.
        let mut buffer = CalibrationBuffer::new(2_000);

        // 1000 old entries generated with true κ = 1.0
        for i in 0..1_000 {
            let rho = -5.0 + 10.0 * (i as f64) / 999.0;
            let p = sigmoid_clamped(rho / 1.0);
            let threshold = ((i % 10) as f64) / 10.0;
            buffer.push(CalibrationEntry {
                rho_eff: rho,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: p > threshold,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        // 1000 new entries generated with true κ = 5.0
        for i in 0..1_000 {
            let rho = -5.0 + 10.0 * (i as f64) / 999.0;
            let p = sigmoid_clamped(rho / 5.0);
            let threshold = ((i % 10) as f64) / 10.0;
            buffer.push(CalibrationEntry {
                rho_eff: rho,
                uncertainty: 0.0,
                anchor_weight: 0.05,
                positive: p > threshold,
                importance_weight: 1.0,
                axis_data: vec![],
            });
        }

        let config = PlattConfig {
            gamma_cal: 0.99,
            ..PlattConfig::default()
        };
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);

        assert!(result.sister_fitted);
        // Recency weighting should pull the fit toward the newer κ = 5.
        // The geometric midpoint is exp((ln1+ln5)/2) ≈ 2.24.  With
        // aggressive γ=0.99, the fit should clearly exceed it.
        assert!(
            result.kappa_sister > 3.0,
            "κ_sister={:.4} should be pulled toward 5.0 by recency, not 1.0",
            result.kappa_sister
        );
    }

    /// The probabilities the fitted constant produces mean what they say: sorted into
    /// deciles, every bin's mean predicted probability sits close to the rate at which
    /// its entries actually turned out adverse. Recovering the right constant is not
    /// the goal in itself — the goal is that a host reading a risk of one in five can
    /// act as though one in five is what it will be.
    ///
    /// ´claim:risk:probabilities-from-the-fitted-constant-match-observed-rates-decile-by-decile´
    /// ´test:unit:calibration-property-decile-bins´
    #[test]
    fn calibration_property_decile_bins() {
        // After fitting, bin predictions into deciles
        // and verify that the empirical positive rate in each bin
        // approximates the bin's mean predicted probability.
        let true_kappa = 2.0;
        let buffer = make_calibrated_entries(true_kappa, 2_000, 0.05);
        let config = PlattConfig::default();
        let result = refit_platt_calibration(&buffer, 1.0, 1.0, &config);
        assert!(result.sister_fitted);

        let fitted_kappa = result.kappa_sister;

        // Collect (predicted_probability, actual_positive) pairs.
        let mut pairs: Vec<(f64, bool)> = buffer
            .iter()
            .map(|e| {
                let p = sigmoid_clamped(e.rho_eff / fitted_kappa);
                (p, e.positive)
            })
            .collect();
        pairs.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap());

        // Bin into 10 deciles.
        let bin_size = pairs.len() / 10;
        let mut max_error = 0.0_f64;

        for bin_idx in 0..10 {
            let start = bin_idx * bin_size;
            let end = if bin_idx == 9 { pairs.len() } else { start + bin_size };
            let bin = &pairs[start..end];

            let mean_predicted: f64 = bin.iter().map(|(p, _)| p).sum::<f64>() / bin.len() as f64;
            let empirical_rate: f64 = bin.iter().filter(|(_, pos)| *pos).count() as f64 / bin.len() as f64;

            let error = (mean_predicted - empirical_rate).abs();
            max_error = max_error.max(error);
        }

        // With 2000 entries and a correctly fitted κ, the worst-bin
        // calibration error should be modest. Allow 0.15 for the
        // deterministic threshold assignment (not truly random).
        assert!(max_error < 0.15, "worst decile calibration error {max_error:.4} exceeds 0.15");
    }
}
